Quiz 1 distribution
========================================================
Before starting an R session, you must call up the R-packages needed for your analysis.

```{r}
library(plyr)
library(ggplot2)
```

Set working directory
```{r}
setwd("/Users/Deborah/desktop/CENG340/grade_dist/Quiz2_dist")

```

Read in data
```{r}
#To import data
abc <- read.table('quiz2.csv', header=FALSE, sep=',')
colnames(abc)<- "grades"
```

I also looked at the data to make sure it was input correctly.

```{r}
abc
```

Plot prob density

```{r fig.width=5.5, fig.height=4.5}
ggplot(abc, aes(x=grades)) + geom_histogram(binwidth = 0.25, fill = "#CC0000") +
  theme(legend.position = "none") +
  theme_bw() +
  ylim(0,13)+
  scale_y_continuous(breaks = 0:12, labels = 0:12)+
  scale_x_continuous(breaks = 4:10, labels = 4:10)+
  theme(axis.text.y = element_text(size = 20, color = "black"),axis.text.x = element_text(size = 20, color = "black"),axis.title.x = element_text(size=20), axis.title.y = element_text(size = 20)) +
  theme(panel.border = element_rect(color = "black"))+
  labs(x = "Quizz Grade (Out of 10)", y = "\nNumber of Students") 
```

